---
  - name: Configuration de SNMP 
    ios_config:
      commands:
        - snmp-server community ansible-manageme RO
        - snmp-server community ansible-manageme RW
  
  - name: Sauvegarde de la configuration
    ios_config:
      save_when: changed

  - name: Sauvegarde de la configuration
    ios_config:
      save_when: changed

        