---
  - name: Configuration du SNMP sur mes équipements
    hosts: all
    gather_facts: false

    pre_tasks:
    - debug:
        msg: "Debut de la configuration"

    roles:
      - snmp

    post_tasks:
    - debug:
        msg: "Equipements configurés"