---
  - name: Restauration du Backup de notre équipement "{{inventory_hostname}}"
    hosts: all
    gather_facts: false

    pre_tasks:
    - debug:
        msg: "Debut de la configuration"

    tasks:
    - name : copie de running config vers l'équipement
      command: scp "backup/{{inventory_hostname}}_config.2021-11-18@20:04:42  scp@{{inventory_hostname}}:{{inventory_hostname}}.config
      # "./backup/{{inventory_hostname}}.config"

    - name : config replace
      ios_commad:
         commands:
            - config replace flash:R1.config force

    post_tasks:
    - debug:
        msg: "Backup restauré"