---

  - name: Configuration du nom des hôtes
    ios_config:
      lines: hostname {{ inventory_hostname }}

  - name: configuration du nom de domaine
    ios_system:  
      domain_name: manageme.org

  - name: configure du DNS lookup sources
    ios_system:
      lookup_enabled: yes

  - name: Configuration de la bannière
    ios_banner:
      banner: motd
      text: "ACCESS AUTORISE !! Ce routeur est la propriete de MANAGEME, SI ERREUR DECONNECTEZ-VOUS"
      state: present
  
  - name: Configuration de la bannière du login
    ios_banner:
      banner: login
      text: |
        Banner of login
        Veuillez vous authentifier
        SVP
      state: present

  - name: Configurer les utilisateurs
    ios_config:
      lines: 
      - username cisco privilege 15 password cisco

  - name: mot de passe enbale
    ios_config:
      lines: 
      - enable secret cisco

  
  - name: crypter les passwords
    ios_config:
      lines: 
      - service password-encryption

  - name: créer une clé ssh
    ios_config:
      lines: 
      - crypto key generate rsa general-keys modulus 2048

  - name: configurer ssh version 2
    ios_config:
      lines: 
      - ip ssh version 2

  - name: limiter les connexions ssh
    ios_config:
      lines: 
      - ip ssh logging events
      - ip ssh time-out 60
      - ip ssh authentication-retries 3

  # Le scp va nous aider plus tard lorsque nous voudrions pousser le backup sur nos équipements
  - name: Configuration du scp 
    ios_config:
      lines:
      - ip scp server enable 
      
  - name: Configurer les ACLs
    ios_config:
      lines: 
      - permit tcp 192.168.80.0 0.0.0.255 any log
      parents: ip access-list extended VTY-ACL
      match: strict
      replace: block
  
  - name: reapplication de VTY-ACL sur les ligne 0 4
    ios_config:
      lines:
      - access-class VTY-ACL in
      parents: line vty 0 4

  - name: Sauvegarde de la configuration
    ios_config:
      save_when: changed