---
  - name: Vérification de l'espace disponible
    hosts: all
    gather_facts: false

    pre_tasks:
    - debug:
        msg: "Debut de l'analyse"

    roles:
      - check_available_space

    post_tasks:
    - debug:
        msg: "Fin de l'analyse"