---
  - name: Configuration du SNMP sur mes équipements
    hosts: all
    gather_facts: false

    pre_tasks:
    - debug:
        msg: "Debut de la configuration"

    roles:
      - transfert_ios

    post_tasks:
    - debug:
        msg: "Fin du transfert"