---
  - name: Backup des routeurs et switchs 
    hosts: all
    gather_facts: false

    pre_tasks:
    - debug:
        msg: "Debut de la configuration"

    tasks:
    - name: Configuration du Backup
      ios_config:
        backup: yes
      register: config_output
    

    # Nous pouvons aussi supprimer cette tâche et garder la première
    - name: Renommage du Backup
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./backup/{{inventory_hostname}}.config"

    - name: Suppression des lignes qui ne sont pas des commandes
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: 'Building configuration.*'
        state: absent

    - name: Suppression des lignes current configuration
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent

    post_tasks:
    - debug:
        msg: "Backup terminé"